name: Sumpwatch
options:
  bundleIdPrefix: com.shimondeitel.sumpwatch
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Sumpwatch:
    type: application
    platform: iOS
    sources:
      - path: Sumpwatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.sumpwatch
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Sumpwatch/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  SumpwatchTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SumpwatchTests
      - path: Sumpwatch.storekit
    dependencies:
      - target: Sumpwatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.sumpwatch.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  SumpwatchUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SumpwatchUITests
    dependencies:
      - target: Sumpwatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.sumpwatch.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Sumpwatch:
    build:
      targets:
        Sumpwatch: all
        SumpwatchTests: [test]
        SumpwatchUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Sumpwatch.storekit
    test:
      config: Debug
      storeKitConfiguration: Sumpwatch.storekit
      targets:
        - SumpwatchTests
        - SumpwatchUITests
    archive:
      config: Release
